apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lmyty91nh-python
  janus-idp.io/tekton: lmyty91nh-python
  backstage.io/kubernetes-id: lmyty91nh-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: lmyty91nh-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
