apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lmyty91nh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lmyty91nh-python 
  name: lmyty91nh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lmyty91nh-python 
